services:
  # -----------------------------------------------------------
  # CONTENEDOR 1: LA BASE DE DATOS MYSQL
  # -----------------------------------------------------------
  db-servicio-1:
    image: mysql:8.0
    container_name: mysql_1
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_micro_1
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3306:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - vol_db_1:/var/lib/mysql
  #
  #Base de datos microservicio 2
  #
  db-servicio-2:
    image: mysql:8.0
    container_name: mysql_2
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_micro_2
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports: 
      - "3307:3306" #el puerto siempre sera 3306, el externo cambia
    networks:
      - red_interna_proyecto
    volumes:
      - vol_db_2:/var/lib/mysql

  #
  #Base de datos microservicio 3
  #
  db-servicio-3:
    image: mysql:8.0
    container_name: mysql_3
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_micro_3
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3308:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - vol_db_3:/var/lib/mysql
  
  #
  #Base de datos microservicio 4
  #
  db-servicio-4:
    image: mysql:8.0
    container_name: mysql_4
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_micro_4
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3309:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - vol_db_4:/var/lib/mysql

  #
  #Base de datos microservicio 5
  #
  db-servicio-5:
    image: mysql:8.0
    container_name: mysql_5
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_micro_5
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3310:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - vol_db_5:/var/lib/mysql
  
  #
  #Base de datos microservicio 6
  #
  db-servicio-6:
    image: mysql:8.0
    container_name: mysql_6
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_micro_6
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3311:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - vol_db_6:/var/lib/mysql

  #
  #Base de datos microservicio 7
  #
  db-servicio-7:
    image: mysql:8.0
    container_name: mysql_7
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_micro_7
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3312:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - vol_db_7:/var/lib/mysql
  
  #
  #Base de datos microservicio 8
  #
  db-servicio-8:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_micro_8
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3313:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - vol_db_8:/var/lib/mysql

  #
  #Base de datos miroservicio 9
  #
  db-servicio-9:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_micro_9
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3314:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - vol_db_9:/var/lib/mysql

  #
  #Base de datos microservicio 10
  #
  db-servicio-10:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: db_micro_10
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3315:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - vol_db_10:/var/lib/mysql
  #   
  # MICROSERVICIO 1: AUTENTICACIÓN (PUERTO 8081)
  #
  auth-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: aduana_auth_container
    ports:
      - "8081:8080"
    depends_on:
      - db-servicio-1
    volumes:
      - ./codigo-fuente/auth-service/auth-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    networks:
      - red_interna_proyecto
  #
  #Microservicio 2: VIAJEROS (Puerto 8082)
  #
  traveler-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: aduana_traveler_container
    ports:
      - "8082:8080"
    depends_on:
      - db-servicio-2
    volumes:
      - ./codigo-fuente/traveler-service/traveler-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    networks:
      - red_interna_proyecto

  #
  #MICROSERVICIO 3: VEHICULOS(Puerto  8083)
  #
  vehicle-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: aduana_vehicle_container
    ports:
     - "8083:8080"
    depends_on:
      - db-servicio-3
    volumes:
      - ./codigo-fuente/vehicle-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    networks:
     - red_interna_proyecto

  #  Micro servicio 4: declaracion(Puerto 8084) 
  #
  #
  declaracion-service: #cambio al español queda preguntar como arreglar los errores ortograficos
    image: maven:3.9-eclipse-temurin-21
    container_name: aduana_declaracion_container
    ports:
      - "8084:8080"
    depends_on:
      - db-servicio-4
    volumes:
      - ./codigo-fuente/declaracion-service/declaracion-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    networks:
      - red_interna_proyecto


  #
  #Micro servico 5: Bodega(Control de inventario)
  #(puerto 8085)
  bodega-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: aduana_bodega_container
    ports:
      - "8085:8080"
    depends_on:
      - db-servicio-5
    volumes:
      - ./codigo-fuente/bodega-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    networks:
      - red_interna_proyecto

  #
  #Microservicio 6: Personal (Gestión de funcionarios)
  #
  personal-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: aduana_personal_container
    ports:
      - "8086:8080"
    depends_on:
      - db-servicio-6
    volumes:
      - ./codigo-fuente/personal-service/personal-service:/app #persistencia en el host
    working_dir: /app
    command: mvn spring-boot:run #Mantiene el contenedor vivo para programar  
    networks:
      - red_interna_proyecto

  #
  #Microservicio 7: Inspección
  #
  inspeccion-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: aduana_inspeccion_container
    ports:
      - "8087:8080"
    depends_on:
      - db-servicio-7
    volumes:
      - ./codigo-fuente/inspeccion-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    networks:
      - red_interna_proyecto

  #
  #Microservicio 8: Seguimiento (Logistia de cargamento)
  #
  seguimiento-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: aduana_seguimiento_container
    ports:
      - "8088:8080"
    depends_on:
      - db-servicio-8
    volumes:
      - ./codigo-fuente/seguimiento-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    networks:
      - red_interna_proyecto

  #
  #Microservicio 9: rutas (Geolocalización fronteriza)
  #
  rutas-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: aduana_rutas_container
    ports:
      - "8089:8080"
    depends_on:
      - db-servicio-9
    volumes:
      - ./codigo-fuente/rutas-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    networks:
      - red_interna_proyecto
  
  #
  #Microservicio 10: Notificaciones (Alertas Viajero)
  #
  noti-service:
    image: maven:3.9-eclipse-temurin-21
    container_name: aduana_noti_container
    ports:
      - "8090:8080"
    depends_on:
      - db-servicio-10
    volumes:
      - ./codigo-fuente/noti-service/noti-service:/app
    working_dir: /app
    command: mvn spring-boot:run
    networks:
      - red_interna_proyecto  


networks:
  red_interna_proyecto:
    driver: bridge

volumes:
  vol_db_1:
  vol_db_2:
  vol_db_3:
  vol_db_4:
  vol_db_5:
  vol_db_6:
  vol_db_7:
  vol_db_8:
  vol_db_9:
  vol_db_10: