spring.application.name=auth-service
server.port=8080

# Credenciales definidas previamente en el docker-compose
spring.datasource.url=jdbc:mysql://db-auth:3306/db_micro_auth
spring.datasource.username=root
spring.datasource.password=tu_clave_maestra
spring.jpa.hibernate.ddl-auto=update

# Configuración de Hibernate para crear tablas automáticamente en base al código
spring.jpa.show-sql=true