spring.application.name=bodega-service
server.port=8080
#Host
spring.datasource.url=jdbc:mysql://db-servicio-5:3306/db_micro_5?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ... Aquí terminan tus líneas actuales ...

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect